-- 1. COUNTRY
CREATE TABLE COUNTRY (
    COUNTRY_ID        INT           NOT NULL,
    COUNTRY_NAME      VARCHAR(100)  NOT NULL,
    COUNTRY_SUBREGION VARCHAR(100)  NOT NULL,
    COUNTRY_REGION    VARCHAR(100)  NOT NULL,
    CONSTRAINT PK_COUNTRY PRIMARY KEY (COUNTRY_ID)
);

USE [2025DBFall_Group_5_DB]
GO

INSERT INTO dbo.COUNTRY (COUNTRY_ID, COUNTRY_NAME, COUNTRY_SUBREGION, COUNTRY_REGION)
SELECT DISTINCT
       COUNTRY_ID,
       COUNTRY_NAME,
       COUNTRY_SUBREGION,
       COUNTRY_REGION
FROM LIY26.dbo.LI_CUSTOMERS_INTX;
GO
