-- 3. PRODUCT
CREATE TABLE PRODUCT (
    PROD_ID             INT             NOT NULL,
    PROD_NAME           VARCHAR(100)    NOT NULL,
    PROD_DESC           VARCHAR(500)    NULL,
    PROD_CATEGORY       VARCHAR(100)    NOT NULL,
    PROD_SUBCATEGORY    VARCHAR(100)    NULL,
    PROD_LIST_PRICE     DECIMAL(18,2)   NOT NULL,
    PROD_MIN_PRICE      DECIMAL(18,2)   NULL,
    PROD_STATUS         VARCHAR(20)     NULL,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PROD_ID),
    CONSTRAINT CK_PRODUCT_LISTPRICE
        CHECK (PROD_LIST_PRICE >= 0),
    CONSTRAINT CK_PRODUCT_MINPRICE
        CHECK (PROD_MIN_PRICE IS NULL OR PROD_MIN_PRICE >= 0),
    CONSTRAINT CK_PRODUCT_STATUS
        CHECK (PROD_STATUS IS NULL OR PROD_STATUS IN ('available','orderable','obsolete'))
);

-- Create non-clustered index on category for aggregation queries
CREATE NONCLUSTERED INDEX IX_PRODUCT_CATEGORY
    ON PRODUCT(PROD_CATEGORY)
    INCLUDE (PROD_LIST_PRICE);
