-- 5. PROMOTION
CREATE TABLE PROMOTION (
    PROMO_ID            INT             NOT NULL,
    PROMO_NAME          VARCHAR(100)    NOT NULL,
    PROMO_SUBCATEGORY   VARCHAR(100)    NULL,
    PROMO_CATEGORY      VARCHAR(100)    NOT NULL,
    PROMO_COST          DECIMAL(18,2)   NULL,
    PROMO_BEGIN_DATE    DATE            NOT NULL,
    PROMO_END_DATE      DATE            NOT NULL,
    CONSTRAINT PK_PROMOTION PRIMARY KEY (PROMO_ID),
    CONSTRAINT CK_PROMOTION_DATES
        CHECK (PROMO_END_DATE >= PROMO_BEGIN_DATE),
    CONSTRAINT CK_PROMOTION_COST
        CHECK (PROMO_COST IS NULL OR PROMO_COST >= 0)
);

-- Index for date range queries
CREATE NONCLUSTERED INDEX IX_PROMOTION_DATES
    ON PROMOTION(PROMO_BEGIN_DATE, PROMO_END_DATE);
