-- 6. SALES (Fact Table)
CREATE TABLE SALES (
    SALE_ID             BIGINT          NOT NULL IDENTITY(1,1),
    CUST_ID             INT             NOT NULL,
    PROD_ID             INT             NOT NULL,
    PROMO_ID            INT             NOT NULL,
    CHANNEL_ID          INT             NOT NULL,
    SALE_DATE           DATE            NOT NULL,
    QUANTITY_SOLD       INT             NOT NULL,
    AMOUNT_SOLD         DECIMAL(18,2)   NOT NULL,
    SHIPPING_DATE       DATE            NULL,
    PAYMENT_DATE        DATE            NULL,

    CONSTRAINT PK_SALES PRIMARY KEY (SALE_ID),

    CONSTRAINT FK_SALES_CUSTOMER
        FOREIGN KEY (CUST_ID)
        REFERENCES CUSTOMER(CUST_ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,

    CONSTRAINT FK_SALES_PRODUCT
        FOREIGN KEY (PROD_ID)
        REFERENCES PRODUCT(PROD_ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,

    CONSTRAINT FK_SALES_PROMOTION
        FOREIGN KEY (PROMO_ID)
        REFERENCES PROMOTION(PROMO_ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,

    CONSTRAINT FK_SALES_CHANNEL
        FOREIGN KEY (CHANNEL_ID)
        REFERENCES LL_CHANNELS(CHANNEL_ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,

    CONSTRAINT CK_SALES_QUANTITY
        CHECK (QUANTITY_SOLD > 0),

    CONSTRAINT CK_SALES_AMOUNT
        CHECK (AMOUNT_SOLD >= 0),

    CONSTRAINT CK_SALES_SHIPPING
        CHECK (SHIPPING_DATE IS NULL OR SHIPPING_DATE >= SALE_DATE),

    CONSTRAINT CK_SALES_PAYMENT
        CHECK (PAYMENT_DATE IS NULL OR PAYMENT_DATE >= SALE_DATE)
);

-- Critical indexes for the Sales fact table
-- Index for date-based queries (BQ01, BQ05)
CREATE NONCLUSTERED INDEX IX_SALES_SALEDATE
    ON SALES(SALE_DATE)
    INCLUDE (PROD_ID, QUANTITY_SOLD, AMOUNT_SOLD);

-- Index for customer analysis (BQ02, BQ04)
CREATE NONCLUSTERED INDEX IX_SALES_CUSTOMER
    ON SALES(CUST_ID)
    INCLUDE (AMOUNT_SOLD, SALE_DATE, SHIPPING_DATE, PAYMENT_DATE);

-- Index for channel performance (BQ03)
CREATE NONCLUSTERED INDEX IX_SALES_CHANNEL
    ON SALES(CHANNEL_ID)
    INCLUDE (AMOUNT_SOLD, QUANTITY_SOLD, PROD_ID);

-- Index for payment analysis (BQ06)
CREATE NONCLUSTERED INDEX IX_SALES_PAYMENT
    ON SALES(PAYMENT_DATE, SALE_DATE)
    INCLUDE (CUST_ID, AMOUNT_SOLD);

-- Composite index for product-date queries
CREATE NONCLUSTERED INDEX IX_SALES_PROD_DATE
    ON SALES(PROD_ID, SALE_DATE)
    INCLUDE (QUANTITY_SOLD, AMOUNT_SOLD);
